-- LaadSmart: tabel `sessies` + RLS (één keer uitvoeren in Supabase → SQL Editor)
-- Verwachte kolommen voor de app: pas_naam, kwh, bedrag, btw, datum

create table if not exists public.sessies (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  pas_naam text not null,
  kwh double precision not null,
  bedrag double precision not null,
  btw double precision not null,
  datum date not null
);

alter table public.sessies add column if not exists pas_naam text;
alter table public.sessies add column if not exists kwh double precision;
alter table public.sessies add column if not exists bedrag double precision;
alter table public.sessies add column if not exists btw double precision;
alter table public.sessies add column if not exists datum date;
alter table public.sessies add column if not exists created_at timestamptz default now();

alter table public.sessies enable row level security;

drop policy if exists "sessies_anon_read_write" on public.sessies;
create policy "sessies_anon_read_write" on public.sessies
  for all
  using (true)
  with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.sessies to anon, authenticated;
